### ISSUE TITLE
Update jobs page layout

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki.com#113]
## Description

The figma design for this is available [here](https://www.figma.com/file/msxmKajRPLYiDDmsP60Ndh/Design-System-v1.1?type=design&node-id=2279-105883&mode=design&t=LPbiXc0jHu307v21-0).

## Tasks

- [x] Introduce index page under `/jobs`
- [x] Decide on how to treat the apply shared part (maybe separate markdown file to load it from) and remove it from each md file
- [x] Adjust the layout
