### ISSUE TITLE
Add playwright tests of payment flows 

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki.com#214]
## Description

We should be able to mock the backend responses to some degree to have some testing for the flows.

## Tasks

- [ ] New Crypto payment
- [ ] Crypto renewal
- [ ] Crypto renewal / with token & chain change
- [ ] Crypto renewal / with plan change
- [ ] Crypto renewal / with plan change / home nav / plan change / token & chain change
